name = "Gamry"
uuid = "7ac59e69-b66b-4d8c-ae34-2aa4271274be"
authors = ["Agustin Pineda"]
version = "0.1.0"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
